env:
  browser: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

plugins:
  - react
  - '@typescript-eslint'

rules:
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/naming-convention': warn
  '@typescript-eslint/no-for-in-array': error
  '@typescript-eslint/no-implied-eval': error
  '@typescript-eslint/no-throw-literal': error
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/no-unnecessary-type-arguments': warn
  '@typescript-eslint/no-unsafe-return': error
  react/prop-types: off

settings:
  react:
    version: detect
