env:
  browser: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

plugins:
  - react
  - '@typescript-eslint'

ignorePatterns:
  - scripts

rules:
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-for-in-array': error
  '@typescript-eslint/no-implied-eval': error
  '@typescript-eslint/no-throw-literal': error
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/no-unnecessary-type-arguments': warn
  '@typescript-eslint/no-unsafe-return': error
  '@typescript-eslint/brace-style': error
  '@typescript-eslint/comma-spacing': error
  '@typescript-eslint/func-call-spacing': error
  object-curly-spacing: [error, always]
  '@typescript-eslint/indent':
    - error
    - 4
    - SwitchCase: 0
  '@typescript-eslint/no-unused-expressions': error
  '@typescript-eslint/no-useless-constructor': error
  '@typescript-eslint/semi': error
  '@typescript-eslint/space-before-function-paren':
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  react/prop-types: off
  react/jsx-indent: [error, 4]
  react/react-in-jsx-scope: off

settings:
  react:
    version: detect
