name: build

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v3
      - run: cd builder && go test -race ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Checkout base branch
        uses: actions/checkout@v3
      - name: Checkout photos branch
        uses: actions/checkout@v3
        with:
          ref: photos
          path: pages/photos

      - name: Build pages
        run: make build

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
