name: Lighthouse Test

on:
  push:

jobs:
  lighthouse:
    name: Lighthouse Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.WORKS_GITHUB_TOKEN }}
          INSTAGRAM_TOKEN: ${{ secrets.PHOTOS_INSTAGRAM_TOKEN }}

      - uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: '.github/workflows/lighthouse.json'
          uploadArtifacts: true
