name: preview

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches-ignore:
      - master
      - photos

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Instal Vercel CLI
        run: npm install --global vercel@latest

      - name: Load artifact
        uses: actions/download-artifact@v4
        with: dist

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        id: deploy
        run: |
          echo -n "url=" >> $GITHUB_OUTPUT
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }} >> $GITHUB_OUTPUT
