name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Cache npm directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - run: npm ci
      - run: npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Cache npm directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - run: npm ci
      - run: npm run lint

  lighthouse:
    name: Lighthouse Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Cache npm directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - name: Cache build directory
        uses: actions/cache@v2
        with:
          path: .next
          key: ${{ runner.os }}-next-${{ hashFiles('**/*.ts') }}-${{ hashFiles('**/*.tsx') }}-${{ hashFiles('**/*.js') }}-${{ hashFiles('**/*.jsx') }}
          restore-keys: ${{ runner.os }}-next-

      - run: npm ci
      - run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.WORKS_GITHUB_TOKEN }}
          INSTAGRAM_TOKEN: ${{ secrets.PHOTOS_INSTAGRAM_TOKEN }}

      - uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: '.github/lighthouse.json'
          uploadArtifacts: true
