name: Triage

on:
  - pull_request

jobs:
  triage:
    name: PR Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
