name: Weekly

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }}
          now-args: '--prod'
          now-org-id: macrat
          now-project-id: ${{ secrets.NOW_PROJECT_ID }}
