name: Weekly

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: deploy
        run: npx now --prod --token $NOW_TOKEN --name $NOW_NAME --confirm
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          NOW_NAME: ${{ secrets.NOW_NAME }}
