name: Weekly

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx now -- --prod --token $NOW_TOKEN
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
