name: Weekly

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: install now
        run: npm i now
      - name: deploy
        run: ./node_modules/.bin/now --prod --token $NOW_TOKEN --confirm
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
